### ISSUE TITLE
project=opensidewalks / project=OpenSidewalks

### ISSUE THREAD

**Issue by matkoniecz** [OpenSidewalks/OpenSidewalks-Schema#9]
I noticed large volume of `project=opensidewalks` and `project=OpenSidewalks` being tagged on OSM objects.

Is it still needed for any purpose? Note that all projects tagging all object of interest does not scale well and is not a good idea.

Do you need help to find all sidewalks within specific area or somehow find subset of sidewalks?

**Comment by nbolten** [comment]
Ah, interesting. I definitely recommend against adding those tags every chance I get. I'll check with the team to see if there's use of an old tool or guide or something.

The only reason they had been used in the past was to keep track of contributions made through our efforts, as tracking that through changesets was a bit of a hurdle and we saw other folks doing it, didn't really know better.

**Comment by nbolten** [comment]
Glad there isn't much in the way of new `project=opensidewalks` tags getting added!

We're 100% on board with that plan, @matkoniecz! We'd actually really appreciate it if you wanted to bot-edit those tags away.

And 100%, changesets is where we're now putting info about whether the data was contributed via one of our specific coordinated efforts.

And thank you for raising this issue!

**Comment by matkoniecz** [comment]
Thanks for info then! I will now proceed further (once I will spend my entertainment time budget on it).

**Comment by galdi** [comment]
Mateusz, we noticed that iD Editor is warning whenever an OSM user finds a marked/unmarked crossing in the bounding box. The warning/suggestion states that a tag is missing, crossing:markings=yes/no, if a feature has been tagged as crossing=marked/unmarked. What is the process to request that a global edit be done so that all already mapped features with crossing=marked/unmarked can have the crossing:markings=yes/no?

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct - requires mailing list interaction

If you can obtain consensus that such edit is worth running I can perform it, but not entirely sure what will be the reaction of people (OSM community is quite bot sceptical, maybe even too much).

Maybe proposing edit limited to USA would be a better idea, and is far more likely to succeed (then asking on US Slack and USA section of official forums would be enough).
